spring:
  application:
    name: crud-service
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_student_ms?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  mybatis:
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: com.example.crud.model
    configuration:
      map-underscore-to-camel-case: true

server:
  port: 8010

eureka:
  instance:
    prefer-ip-address: true

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8888/eureka
