spring:
  application:
    name: auth-service
  cloud:
    config:
      enabled: false

server:
  port: 8087

jwt:
  secret: this-is-a-very-very-long-secret-key-for-jwt-authentication-purposes

eureka:
  instance:
    prefer-ip-address: true

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8888/eureka
