spring:
  application:
    name: crud-client

server:
  port: 8020

eureka:
  instance:
    prefer-ip-address: true

ribbon:
  eureka:
    enable: true

feign:
  client:
    config:
      default:
        connectTimeout: 3000
        readTimeout: 5000

resilience4j:
  circuitbreaker:
    instances:
      fallbackCB:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
  timelimiter:
    instances:
      fallbackCB:
        timeoutDuration: 5s
