apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-client
  namespace: stockmgr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-client
  template:
    metadata:
      labels:
        app: auth-client
    spec:
      containers:
        - name: auth-client
          image: crpi-xxrtggj57h8kwbz2.cn-hangzhou.personal.cr.aliyuncs.com/cloud-native-practice/auth-client:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8086
              protocol: TCP
          env:
            - name: JAVA_OPTS
              value: "-Xmx1g"
            - name: SPRING_PROFILES_ACTIVE
              value: "k8s"
          resources:
            requests:
              cpu: "500m"
              memory: "256Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
          readinessProbe:
            tcpSocket:
              port: 8086
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 8086
            initialDelaySeconds: 60
            periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: auth-client
  namespace: stockmgr
spec:
  selector:
    app: auth-client
  ports:
    - name: http
      port: 8086
      targetPort: 8086
  type: ClusterIP
