apiVersion: apps/v1
kind: Deployment
metadata:
  name: crud-service
  labels:
    app: crud-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: crud-service
  template:
    metadata:
      labels:
        app: crud-service
    spec:
      containers:
        - name: crud-service
          image: crpi-xxrtggj57h8kwbz2.cn-hangzhou.personal.cr.aliyuncs.com/cloud-native-practice/crud-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8010
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: k8s
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8010
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8010
            initialDelaySeconds: 20
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: crud-service
spec:
  selector:
    app: crud-service
  ports:
    - protocol: TCP
      port: 8010
      targetPort: 8010
  type: ClusterIP
