apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service
  namespace: stockmgr
  labels:
    app: gateway-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-service
  template:
    metadata:
      labels:
        app: gateway-service
    spec:
      containers:
        - name: gateway-service
          image: crpi-xxrtggj57h8kwbz2.cn-hangzhou.personal.cr.aliyuncs.com/cloud-native-practice/gateway-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9999
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: k8s
          readinessProbe:
            tcpSocket:
              port: 9999
            initialDelaySeconds: 60
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 9999
            initialDelaySeconds: 60
            periodSeconds: 10
          resources:
            requests:
              cpu: "0.5"
              memory: 256Mi
            limits:
              cpu: "1"
              memory: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  namespace: stockmgr
  labels:
    app: gateway-service
spec:
  type: ClusterIP
  ports:
    - port: 9999
      targetPort: 9999
      protocol: TCP
      name: http
  selector:
    app: gateway-service
