server:
  port: 9999

spring:
  application:
    name: gateway-service
  cloud:
    config:
      enabled: false
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: crud-client
          uri: lb://crud-client
          filters:
            - StripPrefix=1
          predicates:
            - Path=/crud/**

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-service.stockmgr.svc.cluster.local:8888/eureka
