apiVersion: apps/v1
kind: Deployment
metadata:
  name: stats-client
  namespace: stockmgr
spec:
  replicas: 1
  selector:
    matchLabels:
      project: stockmgr
      app: stats-client
  template:
  metadata:
    labels:
      project: stockmgr
      app: stats-client
  spec:
    imagePullSecrets:
      - name: registry-pull-secret
    containers:
      - name: stats-client
        image: registry.cn-hangzhou.aliyuncs.com/my-stock/stats-client:v1.0
        imagePullPolicy: IfNotPresent
        ports:
          - protocol: TCP
            containerPort: 8030
        env:
          - name: JAVA_OPTS
            value: "-Xmx1g"
        resources:
          requests:
            cpu: "0.5"
            memory: 256Mi
          limits:
            cpu: "1"
            memory: 1Gi
        readinessProbe:
          tcpSocket:
            port: 8030
          initialDelaySeconds: 60
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 8030
          initialDelaySeconds: 60
          periodSeconds: 10
