spring:
  application:
    name: stats-service
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_student_ms?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:com/example/stats/mapper/*.xml
  type-aliases-package: com.example.stats.model
  configuration:
    map-underscore-to-camel-case: true

server:
  port: 8030

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8888/eureka
