apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: stockmgr
spec:
  replicas: 2
  selector:
    matchLabels:
      project: stockmgr
      app: auth-service
  template:
    metadata:
      labels:
        project: stockmgr
        app: auth-service
  spec:
    imagePullSecrets:
      - name: registry-pull-secret
    containers:
      - name: auht-service
        image: registry.cn-hangzhou.aliyuncs.com/my-stock/auth-service:v1.0
        imagePullPolicy: IfNotPresent
        ports:
          - protocol: TCP
            containerPort: 8087
        env:
          - name: JAVA_OPTS
            value: "-Xmx1g"
        resources:
          requests:
            cpu: 0.5
            memory: 256Mi
          limits:
            cpu: 1
            memory: 1Gi
        readinessProbe:
          tcpSocket:
            port: 8087
          initialDelaySeconds: 60
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 8087
          initialDelaySeconds: 60
          periodSeconds: 10
